# Replace the title with the name of your restaurant!
title: "Logan's Hotdogs!"
# Write your restaurateur alter ego name below, or your own name
author: Logan Greer 
# Write your Google Analytics tracking ID below
google_analytics: G-P6E4509789

theme: minima

collections:
  explorations:
    output: true
